version: "3"
services:
  applications-db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=applications-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=applications
    restart: always

  applications:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - applications-db
    ports:
      - "8000:8000"
    volumes:
      - ./:/src
    environment:
      - DATABASE_DSN=postgresql://postgres:password@applications-db:5432/applications
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    command: sh -c "alembic upgrade head && uvicorn --host 0.0.0.0 --port 8000 src.main:app"
    restart: always

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  test_applications-db:
    image: postgres:16.2
    environment:
      - POSTGRES_SERVER=test_applications-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_applications
    ports:
      - "5433:5432"

volumes:
  app-db-data: